apiVersion: apps/v1
kind: Deployment
metadata:
  name: flutter-mobile-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flutter-mobile-app
  template:
    metadata:
      labels:
        app: flutter-mobile-app
    spec:
      containers:
        - name: flutter-mobile-app
          image: your-registry/flutter-mobile-app:latest
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-chatbot-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-chatbot-server
  template:
    metadata:
      labels:
        app: flask-chatbot-server
    spec:
      containers:
        - name: flask-chatbot-server
          image: your-registry/flask-chatbot-server:latest
          ports:
            - containerPort: 5000
