// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxHfk7TuPo9irDPQ8JLOHbK6zbCbWLKKE',
    appId: '1:451669329476:web:23177fdb45cdb51e975e11',
    messagingSenderId: '451669329476',
    projectId: 'testchatbotalimipfa',
    authDomain: 'testchatbotalimipfa.firebaseapp.com',
    storageBucket: 'testchatbotalimipfa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfOwt9YWlwUeuKtu53nAmsbgkRAmLjnbk',
    appId: '1:451669329476:android:ca7790426429efdc975e11',
    messagingSenderId: '451669329476',
    projectId: 'testchatbotalimipfa',
    storageBucket: 'testchatbotalimipfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1XanZAtSbYxPuwO5aTxRPbclHbAp9Oi8',
    appId: '1:451669329476:ios:3470af97e7195819975e11',
    messagingSenderId: '451669329476',
    projectId: 'testchatbotalimipfa',
    storageBucket: 'testchatbotalimipfa.appspot.com',
    iosBundleId: 'com.example.careCompanionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1XanZAtSbYxPuwO5aTxRPbclHbAp9Oi8',
    appId: '1:451669329476:ios:3470af97e7195819975e11',
    messagingSenderId: '451669329476',
    projectId: 'testchatbotalimipfa',
    storageBucket: 'testchatbotalimipfa.appspot.com',
    iosBundleId: 'com.example.careCompanionApp',
  );
}
